# Generated by Django 3.2.7 on 2021-09-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='kind',
            field=models.CharField(choices=[('n', 'numbers'), ('c', 'chars'), ('m', 'mixed'), (None, 'choose type')], max_length=1, null=True),
        ),
    ]
