# Generated by Django 3.2.7 on 2021-09-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_board_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='kind',
            field=models.CharField(choices=[(None, 'choose type and value'), ('n', 'numbers'), ('c', 'chars'), ('m', 'Type3')], max_length=1, null=True),
        ),
    ]
