# Generated by Django 3.2.7 on 2021-09-09 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_board_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='kind',
            field=models.CharField(choices=[('type 1', (('n', 'numbers'), ('c', 'chars'))), ('type 2', (('m', 'mixed'),)), (None, 'choose type')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='board.rubric'),
        ),
    ]
