# Generated by Django 3.2.7 on 2021-09-09 17:23

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20210909_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='kind',
            field=models.CharField(choices=[('type 1', (('n', 'numbers'), ('c', 'chars'))), ('type 2', (('m', 'mixed'),)), (None, 'choose type')], max_length=1, null=True, validators=[board.models.validate_kinds]),
        ),
    ]
