# Generated by Django 3.2.7 on 2021-09-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_alter_board_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='kind',
            field=models.CharField(choices=[('type 1', (('n', 'numbers'), ('c', 'chars'))), ('type 2', (('m', 'mixed'),)), (None, 'choose type')], max_length=1, null=True),
        ),
    ]
